name: webf
description: W3C standards-compliant web rendering engine based on Flutter, allowing web applications to run natively on Flutter.
version: 0.14.2-beta.2+1
homepage: https://openwebf.com

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=3.0.5"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.1 # Pure dart module.
  meta: ^1.7.0 # Pure dart module.
  ffi: ^2.0.1 # Pure dart module.
  intl: ^0.18.1 #Pure dart module.
  hive: ^2.2.3
  characters: ^1.2.0
  collection: ^1.16.0
  async: ^2.8.2 # Pure dart module.
  quiver: ^3.2.1 # Pure dart module.
  vector_math: ^2.1.2 # Pure dart module.
  source_span: ^1.9.0 # Pure dart module.
  shared_preferences: 2.2.0 # No AndroidX used.
  archive: ^3.3.7 # Pure dart module.
  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.20.2

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  #
  # NOTE: This new plugin description format is not supported on Flutter's
  # stable channel as of 1.9.1. A plugin published using this format will not
  # work for most clients until the next major stable release.
  # However, it is required in order to declare macOS support.
  plugin:
    platforms:
      android:
        package: com.openwebf.webf
        pluginClass: WebFPlugin
      ios:
        pluginClass: WebFPlugin
      macos:
        pluginClass: WebFPlugin
      linux:
        pluginClass: WebfPlugin
      windows:
        pluginClass: WebfPlugin
