name: Publish WebF To pub.dev

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  nodeVersion: "16"
  cmakeVersion: "3.22.x"
  flutterVersion: "3.24.0"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_macos_binary:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/setup-node@v2
      with:
        node-version: "16"
    - uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: ${{ env.cmakeVersion }}
    - name: NPM INSTALL
      run: npm install
    - name: Build bridge binary
      run: npm run build:bridge:macos:release
    - uses: actions/upload-artifact@v4
      with:
        name: macos_binary
        path: bridge/build/macos/
  build_ios_binary:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/setup-node@v2
      with:
        node-version: "16"
    - uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: ${{ env.cmakeVersion }}
    - name: NPM INSTALL
      run: npm install
    - name: Build bridge binary
      run: npm run build:bridge:ios:release
    - uses: actions/upload-artifact@v4
      with:
        name: ios_binary
        path: bridge/build/ios/
  publish:
    needs: [build_ios_binary, build_macos_binary]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.flutterVersion }}
    - name: NPM INSTALL
      run: npm install
    - uses: actions/download-artifact@v4
      with:
        name: ios_binary
        path: bridge/build/ios/
    - uses: actions/download-artifact@v4
      with:
        name: macos_binary
        path: bridge/build/macos/
    - name: Prepare distribute binaries
      run: node scripts/pre_publish_webf.js
    - run: git log
    - name: Publish
      uses: k-paxian/dart-package-publisher@master
      with:
        credentialJson: ${{ secrets.CREDENTIAL_JSON }}
        force: true
        flutter: true
        skipTests: true
        relativePath: ./webf

